---
#This is workflow name
name: Hello

#runs on a trigger
on:
  push:
    branches:
      - main
#these are jobs inside the workflow
jobs:
#this is the name  of the job
  greet:
#this is github runner
    runs-on: ubuntu-22.04
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"
      - name: say hello to users
        run: echo "Hello $USER"
